name: Docker Build and Deploy

on:
  workflow_call:
    secrets:
      DOCKER_PASSWORD:
        required: true
      DOCKER_USERNAME:
        required: true
      TELEGRAM_BOT_TOKEN:
        required: false
      TELEGRAM_CHAT_ID:
        required: false
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch name to build Docker images for'
        required: false
        default: 'develop'
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  IMAGE_NAME: "trmaphi/freqtrade"
  CACHE_IMAGE: "trmaphi/freqtrade_cache"
  # GHCR_IMAGE_NAME: "ghcr.io/trmaphi/freqtrade"
  # PI_PLATFORM: "linux/arm/v7"

jobs:
  deploy-docker:
    name: "Deploy Docker amd64"
    runs-on: ubuntu-22.04
    if: github.repository == 'trmaphi/freqtrade'

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
        submodules: recursive

    - name: Visualize disk usage before build
      run: df -h

    - name: Cleanup some disk space
      run: |
        docker system prune -a --force || true
        docker builder prune -af || true

    - name: Visualize disk usage after cleanup
      run: df -h

    - name: Set docker tag names
      id: tags
      uses: ./.github/actions/docker-tags

    - name: Login to Docker Hub
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f #v3.12.0

    - name: Available platforms
      run: echo ${PLATFORMS}
      env:
        PLATFORMS: ${{ steps.buildx.outputs.platforms }}

    - name: Build image without cache
      if: github.event_name == 'schedule'
      env:
        TAG: ${{ steps.tags.outputs.TAG }}
      run: |
        docker build -t ${CACHE_IMAGE}:${TAG} .

    # - name: Build ARMHF image without cache
    #   if: github.event_name == 'schedule'
    #   env:
    #     TAG_PI: ${{ steps.tags.outputs.TAG_PI }}
    #     CACHE_TAG_PI: ${{ steps.tags.outputs.CACHE_TAG_PI }}
    #   run: |
    #     docker buildx build \
    #       --cache-to=type=registry,ref=${CACHE_TAG_PI} \
    #       -f docker/Dockerfile.armhf \
    #       --platform ${PI_PLATFORM} \
    #       -t ${IMAGE_NAME}:${TAG_PI} \
    #       --push \
    #       --provenance=false \
    #       .

    - name: Build image with cache
      if: github.event_name != 'schedule'
      env:
        TAG: ${{ steps.tags.outputs.TAG }}
      run: |
        docker pull ${IMAGE_NAME}:${TAG} || true
        docker build --cache-from ${IMAGE_NAME}:${TAG} -t ${CACHE_IMAGE}:${TAG} .

    # - name: Build ARMHF image with cache
    #   if: github.event_name != 'schedule'
    #   # disable provenance due to https://github.com/docker/buildx/issues/1509
    #   env:
    #     TAG_PI: ${{ steps.tags.outputs.TAG_PI }}
    #     CACHE_TAG_PI: ${{ steps.tags.outputs.CACHE_TAG_PI }}
    #   run: |
    #     docker buildx build \
    #       --cache-from=type=registry,ref=${CACHE_TAG_PI} \
    #       --cache-to=type=registry,ref=${CACHE_TAG_PI} \
    #       -f docker/Dockerfile.armhf \
    #       --platform ${PI_PLATFORM} \
    #       -t ${IMAGE_NAME}:${TAG_PI} \
    #       --push \
    #       --provenance=false \
    #       .

    # - name: Run build for AI images
    #   env:
    #     TAG: ${{ steps.tags.outputs.TAG }}
    #     TAG_PLOT: ${{ steps.tags.outputs.TAG_PLOT }}
    #     TAG_FREQAI: ${{ steps.tags.outputs.TAG_FREQAI }}
    #     TAG_FREQAI_RL: ${{ steps.tags.outputs.TAG_FREQAI_RL }}
    #   run: |
    #     docker build --build-arg sourceimage=${CACHE_IMAGE} --build-arg sourcetag=${TAG} -t ${CACHE_IMAGE}:${TAG_PLOT} -f docker/Dockerfile.plot .
    #     docker build --build-arg sourceimage=${CACHE_IMAGE} --build-arg sourcetag=${TAG} -t ${CACHE_IMAGE}:${TAG_FREQAI} -f docker/Dockerfile.freqai .
    #     docker build --build-arg sourceimage=${CACHE_IMAGE} --build-arg sourcetag=${TAG_FREQAI} -t ${CACHE_IMAGE}:${TAG_FREQAI_RL} -f docker/Dockerfile.freqai_rl .


    - name: Run backtest in Docker
      env:
        TAG: ${{ steps.tags.outputs.TAG }}
      run: |
        docker run --rm -v $(pwd)/tests/testdata/config.tests.json:/freqtrade/config.json:ro -v $(pwd)/tests:/tests ${CACHE_IMAGE}:${TAG} backtesting --datadir /tests/testdata --strategy-path /tests/strategy/strats/ --strategy StrategyTestV3

    - name: Push cache images
      env:
        TAG: ${{ steps.tags.outputs.TAG }}
        # TAG_PLOT: ${{ steps.tags.outputs.TAG_PLOT }}
        # TAG_FREQAI: ${{ steps.tags.outputs.TAG_FREQAI }}
        # TAG_FREQAI_RL: ${{ steps.tags.outputs.TAG_FREQAI_RL }}
      run: |
        docker push ${CACHE_IMAGE}:$TAG
        # docker push ${CACHE_IMAGE}:$TAG_PLOT
        # docker push ${CACHE_IMAGE}:$TAG_FREQAI
        # docker push ${CACHE_IMAGE}:$TAG_FREQAI_RL

    - name: Tag and push main image
      env:
        TAG: ${{ steps.tags.outputs.TAG }}
      run: |
        docker tag ${CACHE_IMAGE}:${TAG} ${IMAGE_NAME}:${TAG}
        docker push ${IMAGE_NAME}:${TAG}

    - name: list Images
      run: |
        docker images

    - name: Visualize disk usage after build
      run: df -h

  deploy-arm:
    name: "Deploy Docker ARM64"
    permissions:
      packages: write # Needed to push package versions
    needs: [ deploy-docker ]
    # Only run on 64bit machines
    runs-on: [self-hosted, linux, ARM64]
    if: github.repository == 'trmaphi/freqtrade'

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
        submodules: recursive

    - name: Set docker tag names
      id: tags
      uses: ./.github/actions/docker-tags

    - name: Login to Docker Hub
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build image without cache
      if: github.event_name == 'schedule'
      env:
        TAG_ARM: ${{ steps.tags.outputs.TAG_ARM }}
      run: |
        docker build -t ${IMAGE_NAME}:${TAG_ARM} .

    - name: Build image with cache
      if: github.event_name != 'schedule'
      env:
        TAG_ARM: ${{ steps.tags.outputs.TAG_ARM }}
      run: |
        docker pull ${IMAGE_NAME}:${TAG_ARM} || true
        docker build --cache-from ${IMAGE_NAME}:${TAG_ARM} -t ${CACHE_IMAGE}:${TAG_ARM} .

    - name: Run backtest in Docker
      env:
        TAG_ARM: ${{ steps.tags.outputs.TAG_ARM }}
      run: |
        docker run --rm -v $(pwd)/tests/testdata/config.tests.json:/freqtrade/config.json:ro -v $(pwd)/tests:/tests ${CACHE_IMAGE}:${TAG_ARM} backtesting --datadir /tests/testdata --strategy-path /tests/strategy/strats/ --strategy StrategyTestV3

    - name: Docker images
      run: |
        docker images

    - name: Push cache images
      env:
        TAG_ARM: ${{ steps.tags.outputs.TAG_ARM }}
      run: |
        docker push ${CACHE_IMAGE}:$TAG_ARM

    - name: Create manifests
      env:
        TAG_ARM: ${{ steps.tags.outputs.TAG_ARM }}
        TAG: ${{ steps.tags.outputs.TAG }}
      run: |
        docker buildx imagetools create \
          --tag ${IMAGE_NAME}:${TAG} \
          ${CACHE_IMAGE}:${TAG} ${CACHE_IMAGE}:${TAG_ARM}

    - name: Docker images
      run: |
        docker images

    - name: Image cleanup
      run: |
        docker image prune -a --force --filter "until=24h"

    - name: Telegram notification failure
      if: failure() && ( github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false) && (github.event_name != 'schedule')
      env:
        BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        REPO: ${{ github.repository }}
        BRANCH: ${{ github.ref_name }}
        COMMIT: ${{ github.sha }}
      run: |
        curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
          -d chat_id="${CHAT_ID}" \
          -d text="❌ Freqtrade Docker ARM64 build failed!
        Repository: ${REPO}
        Branch: ${BRANCH}
        Commit: ${COMMIT}" \
          -d parse_mode="HTML"

    - name: Telegram notification success
      if: success() && ( github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false) && (github.event_name != 'schedule')
      env:
        BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        REPO: ${{ github.repository }}
        BRANCH: ${{ github.ref_name }}
        COMMIT: ${{ github.sha }}
      run: |
        curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
          -d chat_id="${CHAT_ID}" \
          -d text="✅ Docker ARM64 build and push Completed!
        Repository: ${REPO}
        Branch: ${BRANCH}
        Commit: ${COMMIT}" \
          -d parse_mode="HTML"
